// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00ZDX5XEMk1zyLnRiAUDgjhaJWD0gnNU',
    appId: '1:321373361342:web:1ce89e0b9affb3dc843aef',
    messagingSenderId: '321373361342',
    projectId: 'projet-forum-296f8',
    authDomain: 'projet-forum-296f8.firebaseapp.com',
    storageBucket: 'projet-forum-296f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrW43NT5-l5eI4XsI6ZMAYbSpG5yA0kJc',
    appId: '1:321373361342:android:e4b030be96260f96843aef',
    messagingSenderId: '321373361342',
    projectId: 'projet-forum-296f8',
    storageBucket: 'projet-forum-296f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpEbT0NAxf9z8qZ-sPQ5m9CLQC-0o8ac',
    appId: '1:321373361342:ios:5a9773245733d63b843aef',
    messagingSenderId: '321373361342',
    projectId: 'projet-forum-296f8',
    storageBucket: 'projet-forum-296f8.appspot.com',
    iosBundleId: 'sn.mouben.idy.projetForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpEbT0NAxf9z8qZ-sPQ5m9CLQC-0o8ac',
    appId: '1:321373361342:ios:5a9773245733d63b843aef',
    messagingSenderId: '321373361342',
    projectId: 'projet-forum-296f8',
    storageBucket: 'projet-forum-296f8.appspot.com',
    iosBundleId: 'sn.mouben.idy.projetForum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD00ZDX5XEMk1zyLnRiAUDgjhaJWD0gnNU',
    appId: '1:321373361342:web:3ddd33830242f192843aef',
    messagingSenderId: '321373361342',
    projectId: 'projet-forum-296f8',
    authDomain: 'projet-forum-296f8.firebaseapp.com',
    storageBucket: 'projet-forum-296f8.appspot.com',
  );

}